node_modules/@financial-times/n-gage/index.mk:
	npm install --no-save --no-package-lock @financial-times/n-gage
	touch $@

-include node_modules/@financial-times/n-gage/index.mk

{{#testAppName}}
TEST_APP := "{{testAppName}}-${CIRCLE_BUILD_NUM}"
{{/testAppName}}
test:
	make verify
